services:
  - type: web
    name: eleven-zero-pb
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/data/eleven_zero_pb.db
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: ENABLE_DEMO_DATA
        value: false
      - key: ENABLE_STARTER_LISTINGS
        value: false
      - key: SITE_URL
        value: https://11zeropb.com
      - key: SUPPORT_EMAIL
        value: 11zeropb@gmail.com
      - key: PRIMARY_OWNER_EMAIL
        value: 11zeropb@gmail.com
      - key: GA_MEASUREMENT_ID
        value: G-SH18CJ4XZD
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_51RgmD8KPW9C7Lp8KHBWIwesr6O2oJkwNtvML9yJJHUGA4IRVuErMDgb0o4Zuwe4FVuuYlgqYrehTqpUU6ORKLQYj00M0lqTfrp
      - key: STRIPE_COUNTRY
        value: US
      - key: PLATFORM_FEE_PERCENT
        value: 8.5
    disk:
      name: eleven-zero-pb-data
      mountPath: /var/data
      sizeGB: 1
